In [0]:
import pandas as pd

perguntas = pd.read_csv("stackoverflow_perguntas.csv")
perguntas.sample(10)

Perguntas          Tags
3697  Eu preciso trocar um texto que está em um CODE...          html
1390  Olá, eu sou meio leigo em PHP vou aprendendo a...          html
4320  Estou criando um site e estou usando angular, ...  html angular
1660  Tenho uma nav com 5 botoes, e um footer com a ...        jquery
3074  não estou conseguindo instalar o jsPDF no meu ...       node.js
309   Como o titulo diz, estou tendo dificuldade par...       angular
1233  O sistema não funciona quando digita número co...        jquery
649   Preciso que ao usuário selecionar uma data na ...         html 
2009  Gostaria de tirar uma dúvida em como comunicar...       node.js
3505  Ao procurar por como renderizar uma CODE  em u...        jquery

In [0]:
print(len(perguntas))

5408


In [0]:
perguntas.Tags.unique()

array(['node.js', 'jquery', 'html', 'html angular ', 'html ', 'angular',
       'angular ', 'jquery html  ', 'jquery ', 'jquery html',
       'jquery html ', 'html angular', 'angular node.js ', 'html  ',
       'jquery html angular', 'node.js ', 'html jquery', 'html jquery ',
       'jquery angular  ', 'html node.js', 'jquery  ', 'angular node.js',
       'jquery angular', 'html node.js ', 'jquery node.js ', 'angular  ',
       'jquery angular ', 'jquery html angular ', 'node.js html ',
       ' node.js', 'node.js html', 'html angular  ', 'jquery node.js',
       'angular html', 'html angular  node.js', 'jquery html node.js',
       'html angular node.js'], dtype=object)

In [0]:
lista_de_tags = list()
for tags in perguntas.Tags.unique():
    for tag in tags.split():
        if tag not in lista_de_tags:
            lista_de_tags.append(tag)
        
print(lista_de_tags)

['node.js', 'jquery', 'html', 'angular']


In [0]:
node_js = list()
for linha_tag in perguntas.Tags:
    if "node.js" in linha_tag:
        node_js.append(1)
    else:
        node_js.append(0)
perguntas["node.js"] = node_js
perguntas

Perguntas           Tags  node.js
0     Possuo um projeto Node.js porém preciso criar ...        node.js        1
1     Gostaria de fazer testes unitários no Node.js,...        node.js        1
2     Como inverter a ordem com que o jQuery itera u...         jquery        0
3     Eu tenho uma página onde pretendo utilizar um ...           html        0
4     Como exibir os dados retornados do FireStore e...  html angular         0
...                                                 ...            ...      ...
5403  Queria saber como pegar o total de cores de um...   jquery html         0
5404  Boa noite, estou usando phonegap para fazer um...          html         0
5405  Estou construindo um mini fórum, e nele, os us...    jquery html        0
5406  Boa tarde,  Estou para desenvolver um site na ...           html        0
5407  Estou fazendo um hotsite, ele é one page, e é ...    jquery html        0

[5408 rows x 3 columns]

In [0]:
def nova_coluna(lista_tags, dataframe, nome_tags):
    for tag in lista_tags:
        coluna = list()
        for linha_tag in dataframe[nome_tags]:
            if tag in linha_tag:
                coluna.append(1)
            else:
                coluna.append(0)
        dataframe[tag] = coluna
nova_coluna(lista_de_tags, perguntas, "Tags")
perguntas.sample(10)

Perguntas  ... angular
5341  Meu código para bloqueio de caracteres esta as...  ...       0
1011  Estou tentando conectar a um banco de teste Fi...  ...       0
5299  Preciso colocar um Carousel(Slider) em uma hom...  ...       0
2912  Galera tenho o seguinte código em jQuery:  COD...  ...       0
1281  Boa tarde, preciso colocar o conteúdo de um po...  ...       0
4236  Galera, é o seguinte: criei um formulário e um...  ...       0
2332  Eu tenho um formulário e ele executa uma actio...  ...       0
2344  Preciso de todas as entidades HTML originais d...  ...       0
301   Tenho o seguinte input file que faz o upload d...  ...       1
1607  Bom, utilizando jquery e js, eu queria fazer u...  ...       0

[10 rows x 6 columns]

In [0]:

from sklearn.model_selection import train_test_split

perguntas_treino, perguntas_test, tags_treino, tags_teste = train_test_split(
    perguntas.Peguntas,
    perguntas.Tags
)

In [0]:
lista_1 = [1,2]
lista_2 = [5,4]
lista_zip = zip(lista_1, lista_2)
print(list(lista_zip))

[(1, 5), (2, 4)]


In [0]:
lista_zip_tags = list(zip(perguntas[lista_de_tags[0]],
                     perguntas[lista_de_tags[1]],
                     perguntas[lista_de_tags[2]],
                     perguntas[lista_de_tags[3]]))

perguntas["todas_tags"] = lista_zip_tags
perguntas.sample(10)

Perguntas  ...    todas_tags
3411  Bom, eu tenho o seguinte código em javascript:...  ...  (0, 0, 1, 0)
4384  Estou procurando uma forma de criar "Máscaras"...  ...  (0, 0, 1, 0)
4333  Eae galera, estou com um probleminha para dar ...  ...  (1, 0, 0, 0)
374   No back end quando faço submit ele apenas me a...  ...  (0, 0, 1, 0)
4407  Estou usando o script skrollr.js em um site e ...  ...  (0, 0, 1, 0)
2498  Estou consumindo uma API através de um método ...  ...  (0, 0, 0, 1)
3788  Estou com problemas ao adicionar a classe no m...  ...  (0, 0, 0, 1)
666   Tenho essa classe no meu CSS:  CODE   Ela não ...  ...  (0, 1, 0, 0)
1498  Possuo uma pagina que ta dando select em php e...  ...  (0, 1, 0, 0)
427   Tenho dois input date criado, e gostaria de pe...  ...  (0, 1, 1, 0)

[10 rows x 7 columns]

In [0]:
lista_de_tags

['node.js', 'jquery', 'html', 'angular']

In [0]:
from sklearn.model_selection import train_test_split

perguntas_treino, perguntas_test, tags_treino, tags_teste = train_test_split(
    perguntas.Perguntas,
    perguntas.todas_tags,
    test_size = 0.2,
    random_state = 123
)

In [0]:
perguntas_treino

1577       array1 = [1,2,3];   array2 = ["um","dois","...
1927    Não sei se fui claro no título, mas quem é da ...
3409    Alguém sabe me dizer qual a melhor forma de re...
4606    Estou com problemas ao tentar validar campos d...
5237    Preciso copiar um valor de dentro de um CODE  ...
                              ...                        
5218    Tenho um sisteminha, para mudar o layout da pá...
4060    Como fazer alto scoll ao carregar a página?  E...
1346    Explicação:  Tenho uma CODE  pai que contém du...
3454    Estou querendo fazer um sistema onde eu iria t...
3582    Galera eu to com um problemão, ja pesquisei ba...
Name: Perguntas, Length: 4326, dtype: object

In [0]:
from sklearn.feature_extraction.text import TfidfVectorizer

vetorizar = TfidfVectorizer(max_features=5000, max_df=0.85)
vetorizar

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=0.85, max_features=5000,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [0]:
vetorizar.fit(perguntas.Perguntas)
perguntas_treino_tfidf = vetorizar.transform(perguntas_treino)
perguntas_test_tfidf = vetorizar.transform(perguntas_test)
print(perguntas_treino_tfidf.shape)
print(perguntas_test_tfidf.shape)

(4326, 5000)
(1082, 5000)


In [0]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import LogisticRegression

regressao_logistica = LogisticRegression()
classificador_onevsrest = OneVsRestClassifier(regressao_logistica)
classificador_onevsrest.fit(perguntas_treino_tfidf, tags_treino)

In [0]:
import numpy as np

tags_treino_array = np.asarray(list(tags_treino))
tags_test_array = np.asarray(list(tags_teste))

In [0]:
tags_treino_array

In [0]:
type(tags_treino)

pandas.core.series.Series

In [0]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import LogisticRegression

regressao_logistica = LogisticRegression()
classificador_onevsrest = OneVsRestClassifier(regressao_logistica)
classificador_onevsrest.fit(perguntas_treino_tfidf, tags_treino)

In [0]:
type(tags_treino)

pandas.core.series.Series

In [0]:
import numpy as np

tags_treino_array = np.asarray(list(tags_treino))
tags_teste_array = np.asarray(list(tags_teste))
print(tags_treino_array)
print(type(tags_treino_array))

[[0 1 0 0]
 [0 1 0 0]
 [0 0 1 0]
 ...
 [0 1 1 0]
 [0 0 1 0]
 [0 1 1 0]]
<class 'numpy.ndarray'>


In [0]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import LogisticRegression

regressao_logistica = LogisticRegression(solver = 'lbfgs')
classificador_onevsrest = OneVsRestClassifier(regressao_logistica)
classificador_onevsrest.fit(perguntas_treino_tfidf, tags_treino_array)
resultado_onevsrest = classificador_onevsrest.score(perguntas_test_tfidf, tags_teste_array)
print("Resultado {0: .2f}%".format(resultado_onevsrest*100))

Resultado  41.68%


In [0]:
perguntas.todas_tags.unique()

array([(1, 0, 0, 0), (0, 1, 0, 0), (0, 0, 1, 0), (0, 0, 1, 1),
       (0, 0, 0, 1), (0, 1, 1, 0), (1, 0, 0, 1), (0, 1, 1, 1),
       (0, 1, 0, 1), (1, 0, 1, 0), (1, 1, 0, 0), (1, 0, 1, 1),
       (1, 1, 1, 0)], dtype=object)

In [0]:
len(perguntas.todas_tags.unique())

13

In [0]:
1/13

0.07692307692307693

In [0]:
from sklearn.metrics import hamming_loss

previsao_onevsrest = classificador_onevsrest.predict(perguntas_test_tfidf)
hamming_loss_onevsrest = hamming_loss(tags_teste_array, previsao_onevsrest)
print("Hamming Loss {0: .2f}".format(hamming_loss_onevsrest))

Hamming Loss  0.19


In [0]:
perguntas.corr()

node.js    jquery      html   angular
node.js  1.000000 -0.321485 -0.273523 -0.101787
jquery  -0.321485  1.000000 -0.253977 -0.366269
html    -0.273523 -0.253977  1.000000 -0.286706
angular -0.101787 -0.366269 -0.286706  1.000000